### ISSUE TITLE
Compat with more geodes reforged?

### ISSUE THREAD

**Issue by CanecaKun** [PurpurMC/PurpurPacks#10]
Hello!

There is a mod called more geodes, that adds geodes for other ores, mainly diamond,emerald and lapis, and it would be amazing if your mods silk touch was compatible with those "budding" block variants too.

https://modrinth.com/mod/more-geodes-reforged

I'm playing on 1.20.1 with purpurpacks-silk-touch-budding-amethyst-1.3 and more-geodes-reforged-1.2.2

Thanks!

**Comment by YouHaveTrouble** [comment]
Supporting modded content is not within the scope of the project.
