### ISSUE TITLE
Compatibility with Divergent Progression?

### ISSUE THREAD

**Issue by Lumb3rSamur4i** [PurpurMC/PurpurPacks#11]
It's possible to have compatibility with divergent progression to use the diamond bars to do the upgrade?
![image](https://github.com/user-attachments/assets/0223426a-d532-44fd-8688-c092aa1442d9)

**Comment by RhythmicSys** [comment]
Unfortunately, adding support for other mods is not within Purpur's scope, as it would become unmanageable and unmaintainable really quickly.

**Comment by RhythmicSys** [comment]
[iron_to_diamond_upgrades.zip](https://github.com/user-attachments/files/16853920/iron_to_diamond_upgrades.zip)
Here's a datapack that will do the same things with the diamond bar, hopefully this is what you need. I won't be able to keep this pack updated if it breaks

**Comment by Lumb3rSamur4i** [comment]
Thanks, ur one of a kind

**Comment by Lumb3rSamur4i** [comment]
[image: image.png]
Thank u a lot
*Alejandro Galeano Torres*
*cc: 1003518347*
*cel: 3014590891*
