### ISSUE TITLE
Enchanting does not work

### ISSUE THREAD

**Issue by Zleph** [PurpurMC/PurpurPacks#14]
I was in my survival world and placed the chiseled bookshelves around the enchanting table, It showed the enchantments but it said "Level requierment: 30"
![2024-11-28_12 32 56](https://github.com/user-attachments/assets/597c3fbf-fa08-4a45-b3e9-5632db679f01)

**Comment by Onako2** [comment]
What datapacks do you use?

**Comment by RhythmicSys** [comment]
Sorry, but you need to have 30 experience levels to use the full enchanting table. The datapack is working as intended, a fully powered enchanting table requires 30 experience levels for a full enchantment. If the datapack was not working, the highest level would be around 5 or 7 experience levels.
