### ISSUE TITLE
Transparent Blocks In Enchant Area v2.0

### ISSUE THREAD

**Issue by fioxu0** [PurpurMC/PurpurPacks#6]
has anyone ever tested this? xdd
just add what's below and I think adding "#minecraft:climbable" is a bad idea in terms of compatibility with other datapacks
![obraz_2024-03-25_043604746](https://github.com/PurpurMC/PurpurPacks/assets/164831377/c1aa1c44-a347-4f95-9801-f5393bbc81d0)

these blocks need to be added
    "#minecraft:corals",
    "#minecraft:inside_step_sound_blocks",
    "#minecraft:wall_corals",
    "minecraft:bamboo",
    "minecraft:bamboo_sapling",
    "minecraft:big_dripleaf",
    "minecraft:cactus",
    "minecraft:chorus_flower",
    "minecraft:chorus_plant",
    "minecraft:dead_brain_coral",
    "minecraft:dead_bubble_coral",
    "minecraft:dead_fire_coral",
    "minecraft:dead_horn_coral",
    "minecraft:dead_tube_coral",
    "minecraft:dead_brain_coral_fan",
    "minecraft:dead_bubble_coral_fan",
    "minecraft:dead_fire_coral_fan",
    "minecraft:dead_horn_coral_fan",
    "minecraft:dead_tube_coral_fan",
    "minecraft:dead_brain_coral_wall_fan",
    "minecraft:dead_bubble_coral_wall_fan",
    "minecraft:dead_fire_coral_wall_fan",
    "minecraft:dead_horn_coral_wall_fan",
    "minecraft:dead_tube_coral_wall_fan",
    "minecraft:enchanting_table",
    "minecraft:cocoa",
    "minecraft:frogspawn",
    "minecraft:iron_bars",
    "minecraft:lily_pad",
    "minecraft:nether_wart",
    "minecraft:kelp",
    "minecraft:piston_head",
    "minecraft:redstone_wall_torch",
    "minecraft:sea_pickle",
    "minecraft:small_dripleaf",
    "minecraft:sniffer_egg",
    "minecraft:soul_wall_torch",
    "minecraft:sugar_cane",
    "minecraft:sweet_berry_bush",
    "minecraft:turtle_egg",
    "minecraft:wall_torch"

shulker boxes, it's practical
    "#minecraft:shulker_boxes"
 
I'm not sure about these blocks
    "minecraft:beacon",
    "minecraft:spawner",
    "minecraft:tinted_glass"

**Comment by fioxu0** [comment]
I'm frustrated because I downloaded this datapack to be able to place lily pads around the enchanting table
![obraz_2024-03-25_044640903](https://github.com/PurpurMC/PurpurPacks/assets/164831377/106bbd46-1f11-4e85-95bb-51d1b8290043)

**Comment by RhythmicSys** [comment]
> has anyone ever tested this?
Yes, unfortunately Minecraft having 879 blocks and constantly adding more of them makes it difficult to test properly. I'll adjust this, I didn't get the notification until just now

**Comment by RhythmicSys** [comment]
Should be resolved now in version [2.1](https://modrinth.com/datapack/purpurpacks-transparent-blocks-in-enchant-area/version/2.1)
![Mar_26_2024_16-46-38](https://github.com/PurpurMC/PurpurPacks/assets/45906780/edb1f3f7-7b9c-4bd0-8a4b-254217fcdd4d)
